delta_t: 0.25
max_step: 8
max_simulation_time: 20

# environment
map_size: 25
lane_width: 4

# mcts parameters
computation_budget: 15000
lamda: 0.9
weight_avoid: 20
weight_safe: 0.2
weight_offroad: 2
weight_direction: 1
weight_distance: 0.1
weight_velocity: 0.03

# visualization parameters
# realistic or linestyle
vehicle_display_style: "linestyle"
is_show_predict_traj: false

vehicle_list:
  vehilce_1:
    level: 1
    init:
      x:
        min: -2
        max: -2
      y:
        min: 12
        max: 20
      yaw: -1.5707963
      v:
        min: 3
        max: 5
    target:
      x: -2
      y: -18
      yaw: -1.5707963
    text:
      x: 10
      y: 15
  vehilce_2:
    level: 0
    init:
      x:
        min: -20
        max: -12
      y:
        min: -2
        max: -2
      yaw: 0
      v:
        min: 3
        max: 5
    target:
      x: 18
      y: -2
      yaw: 0
    text:
      x: -20
      y: -15
